version: 2
jobs:
  build:
    working_directory: ~/Python-Pomodoro-Timer
    docker:
      - image: circleci/python:3.6.1
    
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install
